apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: mybookapi
    labels:
      app: mybookapi
spec:
  replicas: 2
  template:
    metadata:
      labels:
        # This is the label for the pods.
        app: mybookapi
        tier: service
    spec:
      containers:
      - name: mybookapi
        image: "mybooapi:1.0.0-alpine"
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        resources:
          requests:
            memory: "64Mi"
            cpu: "125m"
          limits:
            memory: "128Mi"
            cpu: "250m"